const myWork = [
  {
    category: "logo",
    description: "Shaulina",
    thumbnail: "images/work/logos/saulina/saulina-thumb.jpg",
    images: [
      "images/work/logos/saulina/saulina1.jpg",
      "images/work/logos/saulina/saulina3.jpg",
      "images/work/logos/saulina/saulina4.jpg",
      "images/work/logos/saulina/saulina5.jpg",
      "images/work/logos/saulina/saulina6.jpg",
      "images/work/logos/saulina/saulina7.jpg",
    ],
  },
  {
    category: "logo",
    description: "Vulic",
    thumbnail: "images/work/logos/vulic/vulic-thumb.jpg",
    images: [
      "images/work/logos/vulic/vul01.jpg",
      "images/work/logos/vulic/vul02.jpg",
      "images/work/logos/vulic/vul03.jpg",
      "images/work/logos/vulic/vul04.jpg",
      "images/work/logos/vulic/vul05.jpg",
      "images/work/logos/vulic/vul06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Zoe",
    thumbnail: "images/work/logos/zoe/zoe-thumb.jpg",
    images: [
      "images/work/logos/zoe/zoe01.jpg",
      "images/work/logos/zoe/zoe02.jpg",
      "images/work/logos/zoe/zoe03.jpg",
      "images/work/logos/zoe/zoe04.jpg",
      "images/work/logos/zoe/zoe05.jpg",
      "images/work/logos/zoe/zoe06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Mediceva",
    thumbnail: "images/work/logos/mediceva/med-thumb.jpg",
    images: [
      "images/work/logos/mediceva/med1.jpg",
      "images/work/logos/mediceva/med2.jpg",
      "images/work/logos/mediceva/med3.jpg",
      "images/work/logos/mediceva/med04.jpg",
      "images/work/logos/mediceva/med05.jpg",
      "images/work/logos/mediceva/med06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Pet",
    thumbnail: "images/work/logos/pet/pet-thumb.jpg",
    images: [
      "images/work/logos/pet/pet01.jpg",
      "images/work/logos/pet/pet02.jpg",
      "images/work/logos/pet/pet03.jpg",
      "images/work/logos/pet/pet04.jpg",
      "images/work/logos/pet/pet05.jpg",
      "images/work/logos/pet/pet06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Web",
    thumbnail: "images/work/logos/web/web-thumb.jpg",
    images: [
      "images/work/logos/web/web01.jpg",
      "images/work/logos/web/web02.jpg",
      "images/work/logos/web/web03.jpg",
      "images/work/logos/web/web04.jpg",
      "images/work/logos/web/web05.jpg",
      "images/work/logos/web/web06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Zaz",
    thumbnail: "images/work/logos/zaz/zaz-thumb.jpg",
    images: [
      "images/work/logos/zaz/zaz01.jpg",
      "images/work/logos/zaz/zaz02.jpg",
      "images/work/logos/zaz/zaz03.jpg",
      "images/work/logos/zaz/zaz04.jpg",
      "images/work/logos/zaz/zaz05.jpg",
      "images/work/logos/zaz/zaz06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Team",
    thumbnail: "images/work/logos/team/team-thumb.jpg",
    images: [
      "images/work/logos/team/team01.jpg",
      "images/work/logos/team/team02.jpg",
      "images/work/logos/team/team03.jpg",
      "images/work/logos/team/team04.jpg",
      "images/work/logos/team/team05.jpg",
      "images/work/logos/team/team06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Craft",
    thumbnail: "images/work/logos/craft/craft-thumb.jpg",
    images: [
      "images/work/logos/craft/craft01.jpg",
      "images/work/logos/craft/craft02.jpg",
      "images/work/logos/craft/craft03.jpg",
      "images/work/logos/craft/craft04.jpg",
      "images/work/logos/craft/craft05.jpg",
      "images/work/logos/craft/craft06.jpg",
    ],
  },
  {
    category: "logo",
    description: "Velepromet",
    thumbnail: "images/work/logos/vel/vel-thumb.jpg",
    images: [
      "images/work/logos/vel/vel01.jpg",
      "images/work/logos/vel/vel02.jpg",
      "images/work/logos/vel/vel03.jpg",
      "images/work/logos/vel/vel04.jpg",
      "images/work/logos/vel/vel05.jpg",
      "images/work/logos/vel/vel06.jpg",
    ],
  },
  {
    category: "illustrations",
    description: "Stickers",
    thumbnail: "images/work/illustrations/stikers/stiker-thumb.jpg",
    images: [
      "images/work/illustrations/stikers/stiker01.jpg",
      "images/work/illustrations/stikers/stiker02.jpg",
      "images/work/illustrations/stikers/stiker03.jpg",
      "images/work/illustrations/stikers/stiker04.jpg",
      "images/work/illustrations/stikers/stiker05.jpg",
      "images/work/illustrations/stikers/stiker06.jpg",
      "images/work/illustrations/stikers/stiker07.jpg",
      "images/work/illustrations/stikers/stiker08.jpg",
      "images/work/illustrations/stikers/stiker09.jpg",
      "images/work/illustrations/stikers/stiker10.jpg",
    ],
  },
  {
    category: "illustrations",
    description: "Shirts",
    thumbnail: "images/work/illustrations/majice/majica-thumb.jpg",
    images: [
      "images/work/illustrations/majice/beli01.jpg",
      "images/work/illustrations/majice/beli02.jpg",
      "images/work/illustrations/majice/beli03.jpg",
      "images/work/illustrations/majice/beli04.jpg",
      "images/work/illustrations/majice/beli05.jpg",
      "images/work/illustrations/majice/beli06.jpg",
      "images/work/illustrations/majice/beli07.jpg",
    ],
  },
  {
    category: "illustrations",
    description: "Stara Planina",
    thumbnail: "images/work/illustrations/staraplanina/planina-thumb.jpg",
    images: [
      "images/work/illustrations/staraplanina/planina01.jpg",
      "images/work/illustrations/staraplanina/planina02.jpg",
      "images/work/illustrations/staraplanina/planina03.jpg",
      "images/work/illustrations/staraplanina/planina04.jpg",
    ],
  },
  {
    category: "banners",
    description: "ITA",
    thumbnail: "images/work/banners/banner1/banner1-thumb.jpg",
    images: ["images/work/banners/banner1/banner-ita.jpg"],
  },
  {
    category: "banners",
    description: "Banner 2",
    thumbnail: "images/work/banners/banner2/banner2-thumb.jpg",
    images: ["images/work/banners/banner2/banner2.jpg"],
  },
  {
    category: "banners",
    description: "Banner 3",
    thumbnail: "images/work/banners/banner3/banner3-thumb.jpg",
    images: ["images/work/banners/banner3/banner3.jpg"],
  },
  {
    category: "banners",
    description: "Banner 4",
    thumbnail: "images/work/banners/banner4/banner4-thumb.jpg",
    images: ["images/work/banners/banner4/banner4.jpg"],
  },
  {
    category: "banners",
    description: "Banner 5",
    thumbnail: "images/work/banners/banner5/banner5-thumb.jpg",
    images: ["images/work/banners/banner5/banner5.jpg"],
  },
  {
    category: "banners",
    description: "Banner 6",
    thumbnail: "images/work/banners/banner6/banner6-thumb.jpg",
    images: ["images/work/banners/banner6/banner6.jpg"],
  },
  {
    category: "banners",
    description: "Banner 7",
    thumbnail: "images/work/banners/banner7/banner7-thumb.jpg",
    images: ["images/work/banners/banner7/banner7.jpg"],
  },
  {
    category: "banners",
    description: "Banner 8",
    thumbnail: "images/work/banners/banner8/banner8-thumb.jpg",
    images: ["images/work/banners/banner8/banner8.jpg"],
  },
  {
    category: "banners",
    description: "Banner 9",
    thumbnail: "images/work/banners/banner9/banner9-thumb.jpg",
    images: ["images/work/banners/banner9/banner9.jpg"],
  },
  {
    category: "banners",
    description: "Banner 10",
    thumbnail: "images/work/banners/banner10/banner10-thumb.jpg",
    images: ["images/work/banners/banner10/banner10.jpg"],
  },
  {
    category: "mockups",
    description: "Atlas",
    thumbnail: "images/work/mockups/atlas/atlas-thumb.jpg",
    images: [
      "images/work/mockups/atlas/atlas01.jpg",
      "images/work/mockups/atlas/atlas02.jpg",
      "images/work/mockups/atlas/atlas03.jpg",
      "images/work/mockups/atlas/atlas04.jpg",
      "images/work/mockups/atlas/atlas05.jpg",
      "images/work/mockups/atlas/atlas06.jpg",
    ],
  },
  {
    category: "brochures",
    description: "Brochure 1",
    thumbnail: "images/work/brochures/brosura1/brosura-thumb.jpg",
    images: [
      "images/work/brochures/brosura1/brosura01.jpg",
      "images/work/brochures/brosura1/brosura02.jpg",
      "images/work/brochures/brosura1/brosura03.jpg",
      "images/work/brochures/brosura1/brosura04.jpg",
      "images/work/brochures/brosura1/brosura05.jpg",
      "images/work/brochures/brosura1/brosura06.jpg",
    ],
  },
  {
    category: "social-networks",
    description: "IM Clinic",
    thumbnail: "images/work/social-networks/im/im-thumb.jpg",
    images: [
      "images/work/social-networks/im/im01.jpg",
      "images/work/social-networks/im/im02.jpg",
      "images/work/social-networks/im/im03.jpg",
      "images/work/social-networks/im/im04.jpg",
      "images/work/social-networks/im/im05.jpg",
      "images/work/social-networks/im/im06.jpg",
    ],
  },
  {
    category: "social-networks",
    description: "Maestro",
    thumbnail: "images/work/social-networks/comp/comp-thumb.jpg",
    images: [
      "images/work/social-networks/comp/comp01.jpg",
      "images/work/social-networks/comp/comp02.jpg",
      "images/work/social-networks/comp/comp03.jpg",
      "images/work/social-networks/comp/comp04.jpg",
      "images/work/social-networks/comp/comp05.jpg",
      "images/work/social-networks/comp/comp06.jpg",
    ],
  },
  {
    category: "social-networks",
    description: "Computer Land",
    thumbnail: "images/work/social-networks/maestro/maestro03.jpg",
    images: [
      "images/work/social-networks/maestro/maestro01.jpg",
      "images/work/social-networks/maestro/maestro02.jpg",
      "images/work/social-networks/maestro/maestro03.jpg",
      "images/work/social-networks/maestro/maestro04.jpg",
      "images/work/social-networks/maestro/maestro05.jpg",
      "images/work/social-networks/maestro/maestro06.jpg",
    ],
  },
  {
    category: "social-networks",
    description: "Comono",
    thumbnail: "images/work/social-networks/comono/comono-thumb.jpg",
    images: [
      "images/work/social-networks/comono/comono01.jpg",
      "images/work/social-networks/comono/comono02.jpg",
      "images/work/social-networks/comono/comono03.jpg",
      "images/work/social-networks/comono/comono04.jpg",
      "images/work/social-networks/comono/comono05.jpg",
      "images/work/social-networks/comono/comono06.jpg",
    ],
  },
];
